version: "3.8"

services:
  go_dev:
    image: go_dev:latest
    container_name: go_dev
    build:
      context: .
      # Correct the path to your Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN:-token}
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app

    networks:
      - net101

networks:
  net101:
    name: net101
    external: true